### ISSUE TITLE
errors by running dress_code while using docker

### ISSUE THREAD

**Issue by huangdengpan** [instructure/dress_code#5]
when I trying to run RAILS_ENV=production bundle exec rake canvas:compile_assets in docker (ubuntu 18.04)

It shows the error like :

Done in 42.90s.
Done in 52.01s.
--> Finished: 'js:yarn_install' in 52.28s
rake aborted!
Parallel::UndumpableException: RuntimeError: error running dress_code
/opt/canvas/lib/tasks/css.rake:28:in block (2 levels) in <top (required)>`
...

Could someone help me ?

**Comment by huangdengpan** [comment]
Traceback (most recent call last):
	10: from bin/dress_code:18:in `<main>'
	 9: from bin/dress_code:18:in `load'
	 8: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/bin/dress_code:88:in `<top (required)>'
	 7: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:16:in `extract'
	 6: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:21:in `parse_files'
	 5: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:21:in `flat_map'
	 4: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:21:in `each'
	 3: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:21:in `block in parse_files'
	 2: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:26:in `parse_file'
	 1: from /opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:32:in `scan'
/opt/canvas/vendor/bundle/ruby/2.6.0/gems/dress_code-1.2.0/lib/dress_code/extractor.rb:32:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
